### PR TITLE
Update configurations and docker version

### PR DESCRIPTION
**Pull request by jpalawaga**
I've provided some additional configurations which you may/may not want to accept.

Given the nature of private RTD instances, I figure that it makes sense to include that configuration. I also had to add a couple lines to get my SSH key working correctly. I've also included a sample docker-compose file that shouldn't contain any proprietary information.

I've tested the update and it seems to work fine with the docker instance. The only thing is that you need to make sure to run the migrations if you're not starting clean.

### CODE REVIEW

**Comment by InAnimaTe** [comment]
This is awesome work dude. I really appreciate you taking the initiative to get this docker image working properly with updates etc..

Just a couple things before I accept:
- It'd be really nice to write a short README to help people get started. You can talk about the additional configuration you've added and how to launch using the included `docker-compose.yml` file.
- Let's change the local_settings file to `local_settings.py.example` just so we aren't by default applying settings people may not want to use.

Thanks for the commits!

**Comment by jpalawaga** [comment]
@InAnimaTe take a peek when you have a moment!

**Comment by InAnimaTe** [comment]
Looking good! Thanks a ton for the work!

**Comment by InAnimaTe** [comment]
Uh ohh! @jpalawaga this happened at build time:

https://hub.docker.com/r/inanimate/rtd/builds/bm8rwnkzunwaw9jrcpmbyxv/

**Comment by jpalawaga** [comment]
Looks like it's broken because the docker build needs a concrete local_settings.py, but that is no longer being provided. I can rename the file back, or revert the changes to that file.

**Comment by InAnimaTe** [comment]
So I fixed the Dockerfile (and updated readme) so we could provide a base to start with where people could bind-mount in keys and/or local_settings. Build is now successful ;)

**Comment by jpalawaga** [comment]
@InAnimaTe fabulous! good stuff 🤘

**Pull request merged**
